In [1]:
from platform import platform, python_version

print(f'Platform: {platform()}')
print(f'Python version: {python_version()}')

Platform: Linux-5.15.0-170-generic-x86_64-with-glibc2.35
Python version: 3.13.5


In [2]:
%pip install --quiet --upgrade pip pandas numpy matplotlib seaborn watermark

Note: you may need to restart the kernel to use updated packages.


In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import watermark

import warnings
warnings.filterwarnings(action='ignore', category=FutureWarning)

plt.style.use(style='ggplot')
%matplotlib inline

In [4]:
%reload_ext watermark
%watermark -a 'Fernando Galvão | 01 - Libraries for Exploratory Data Analysis' -d -t -v -m -p pandas,numpy,matplotlib,seaborn,watermark

Author: Fernando Galvão | 01 - Libraries for Exploratory Data Analysis

Date/Time: 2026-02-14 18:08:02

Python implementation: CPython
Python version       : 3.13.5
IPython version      : 9.10.0

pandas    : 3.0.0
numpy     : 2.4.2
matplotlib: 3.10.8
seaborn   : 0.13.2
watermark : 2.6.0

Compiler    : GCC 11.2.0
OS          : Linux
Release     : 5.15.0-170-generic
Machine     : x86_64
Processor   : x86_64
CPU cores   : 8
Architecture: 64bit



In [18]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [19]:
print(f'arr_1d: \n{arr_1d}')
print('\n')
print(f'arr_2d: \n{arr_2d}')

arr_1d: 
[1 2 3 4 5]


arr_2d: 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
print(f'arr_1d - type: {type(arr_1d)}')
print(f'arr_2d - type: {type(arr_2d)}')

arr_1d - type: <class 'numpy.ndarray'>
arr_2d - type: <class 'numpy.ndarray'>


In [21]:
print(f'arr_1d - dimension: {arr_1d.ndim}')
print(f'arr_2d - dimension: {arr_2d.ndim}')

arr_1d - dimension: 1
arr_2d - dimension: 2


In [22]:
print(f'arr_1d - shape: {arr_1d.shape}')
print(f'arr_2d - shape: {arr_2d.shape}')

arr_1d - shape: (5,)
arr_2d - shape: (2, 5)
